// HLC timestamp structure
export interface HLCTimestamp {
  timestamp: number  // Physical time component
  counter: number    // Logical counter for same timestamp
  nodeId: string     // Node identifier (client-a, client-b, server)
}

// Field with HLC tracking
export interface HLCField<T> {
  value: T
  hlc: HLCTimestamp
}

// Ticket structure
export interface Ticket {
  id: string
  fields: {
    ticket_name: HLCField<string>
    dummy_field: HLCField<string>
  }
}

// Node types
export type NodeId = 'client-a' | 'client-b' | 'server'

// Message types for sync
export type MessageType = 'push' | 'pull' | 'broadcast' | 'update' | 'create'

// Partial ticket for delta updates
export interface TicketDelta {
  id: string
  fields: Partial<Ticket['fields']>
}

export interface BaseMessage {
  id: string
  from: NodeId
  to: NodeId
  timestamp: number
  revision?: number
}

export interface BatchMessage extends BaseMessage {
  type: 'push' | 'pull' | 'broadcast'
  tickets: TicketDelta[]
}

export interface FieldUpdateMessage extends BaseMessage {
  type: 'update'
  entity_id: string
  field: string
  value: string
  hlc: HLCTimestamp
}

export interface TicketCreateMessage extends BaseMessage {
  type: 'create'
  ticket: Ticket
}

export interface RejectionMessage extends BaseMessage {
  type: 'rejection'
  originalMessageId: string
  entity_id: string
  field: string
  value: string
  existingValue: string // The current server value to revert to
  reason: string
  rule: string // The rule that triggered rejection
}

export type SyncMessage = BatchMessage | FieldUpdateMessage | TicketCreateMessage | RejectionMessage

// Represents a single condition to evaluate
export interface RejectionCondition {
  // Left side: what to check
  source: 'incoming' | 'existing'  // Check the incoming update value or existing field value
  field: string                     // Field name (e.g., "dummy_field")

  // Operator
  operator: 'equals' | 'not_equals'

  // Right side: what to compare against
  // Use compareToField for cross-field comparison, OR value for literal comparison
  compareToField?: {
    source: 'incoming' | 'existing'
    field: string
  }
  value?: string  // Literal value (used if compareToField not set)
}

// A rule contains one or more conditions (all must match - AND logic)
export interface RejectionRule {
  id: string
  name: string                      // Human-readable name for display
  conditions: RejectionCondition[]  // All conditions must match
  enabled: boolean
}

// Node state
export interface NodeState {
  nodeId: NodeId
  currentTime: number  // Static time that can be edited
  isOnline: boolean    // Device-level connectivity
  isAppOnline: boolean // App-level running state
  tickets: Ticket[]
  inbox: SyncMessage[]
  outbox: SyncMessage[]
  modifiedTicketIds: string[] // IDs of tickets modified locally since last sync
  modifiedFields: Record<string, string[]> // Map of ticketId -> array of field names modified
  lastHLC: HLCTimestamp // Highest HLC timestamp seen or generated by this node
  serverRevision?: number // Server only, tracks current revision
  lastSeenServerRevision?: number // Clients only, tracks last processed server revision
  eventBuffer?: SyncMessage[] // Server only, history of mutations
  rejectionRules?: RejectionRule[] // Server only, business logic rules
  highlightedFields: Record<string, boolean> // Map of "ticketId:fieldName" -> boolean
}

// Log entry
export interface LogEntry {
  timestamp: number
  nodeId: NodeId
  action: string
  details: string
  data?: any
}
